version: '3.8'

services:
  ledger:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: simple-ledger
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped

